# Hexagonal sticker for the 'sdetorus' package.
#
# The badge is built from an intermediate frame of the torus-diffusion animation
# (sdetorus.gif, generated by sdetorus-logo.R): the "sdetorus" wordmark is
# treated as a density and evolved by a Crank-Nicolson PDE, so at an intermediate
# step it appears as a colourful density heatmap (MATLAB "jet" colormap) that
# still reads as "sdetorus". This diffused wordmark *is* the badge, so no crisp
# package name is overlaid on top. The torus fundamental domain is a periodic
# square, which is why the square frame fills the whole hexagon (full-bleed).
#
# Run from the package root:
#
#   Rscript logo/logo.R
#
# Output: logo/logo.png (master) and man/figures/logo.png (shipped mirror).
# Requires: magick, hexSticker.

library(magick)
library(hexSticker)

## ---- Shared logo standard (identical across egarpor packages) -------------
# Aller_Rg is bundled with (and auto-registered by) hexSticker, so no
# showtext/font_add setup is needed. sdetorus stays intentionally nameless --
# the diffused wordmark already lives in the frame -- so only the GitHub URL
# uses these shared constants.
FONT    <- "Aller_Rg"   # typeface for the GitHub URL
U_SIZE  <- 9.0          # GitHub URL size (large enough to read)
U_X     <- 1.00         # GitHub URL position: along the lower-right hex edge
U_Y     <- 0.08
U_ANGLE <- 30
H_SIZE  <- 1.5          # hexagon border thickness
DPI     <- 600

## ---- Parameters -------------------------------------------------------------

gif_file  <- "logo/sdetorus.gif"
frame_idx <- 84            # intermediate diffusion step (of 200): wordmark is
                           # sharp yet still a density, with a touch of warm jet
                           # accent. Try ~110 for a bolder, cooler variant.
border    <- "#08519C"     # deep jet-blue (cool end of matlab.like2)
fill      <- "#08306B"     # dark navy (mostly hidden behind the full-bleed frame)
ghurl     <- "github.com/egarpor/sdetorus"   # runs along the lower-right edge
out_logo  <- "logo/logo.png"
out_man   <- "man/figures/logo.png"

## ---- 1. Intermediate frame from the diffusion gif ---------------------------

g     <- image_read(gif_file)
frame <- image_convert(g[frame_idx], "png")
frame <- image_resize(frame, "1000x1000", filter = "Lanczos")   # smooth upscale
ftmp  <- tempfile(fileext = ".png")
image_write(frame, ftmp, format = "png")

## ---- 2. Full-bleed hex sticker ----------------------------------------------

# hexSticker does not clip an oversized subplot to the hexagon, so a full-bleed
# square spills into the corners. We render (a) the full-bleed sticker and (b) a
# hexagon-only sticker with the same geometry, then use (b)'s silhouette as an
# alpha mask to crop (a) cleanly to the hexagon while keeping the border.
render <- function(subplot, s_width, url, file) {
  sticker(subplot = subplot, s_x = 1, s_y = 1,
          s_width = s_width, s_height = s_width,
          package = "",                         # wordmark already lives in the frame
          h_fill = fill, h_color = border, h_size = H_SIZE,
          url = url, u_x = U_X, u_y = U_Y, u_angle = U_ANGLE,  # diagonal, lower-right edge
          u_size = U_SIZE, u_color = "#FFFFFF", u_family = FONT,
          filename = file, dpi = DPI)
  invisible(file)
}

full_f <- tempfile(fileext = ".png")
render(ftmp, 1.0, ghurl, full_f)

blank  <- image_blank(4, 4, color = "none")     # transparent -> pure hex silhouette
btmp   <- tempfile(fileext = ".png")
image_write(blank, btmp, format = "png")
mask_f <- tempfile(fileext = ".png")
render(btmp, 0.1, "", mask_f)                   # no url on the mask (pure silhouette)

sticker_img <- image_composite(image_read(full_f), image_read(mask_f),
                               operator = "CopyOpacity")
image_write(sticker_img, out_logo, format = "png")

## ---- 3. Mirror to the conventional man/figures/logo.png ---------------------

dir.create(dirname(out_man), showWarnings = FALSE, recursive = TRUE)
image_write(sticker_img, out_man, format = "png")

message("Wrote ", out_logo, " and ", out_man,
        " (", image_info(sticker_img)$width, "x",
        image_info(sticker_img)$height, ")")
