# Hexagonal sticker for the 'sdetorus' package.
#
# The badge is built from an intermediate frame of the torus-diffusion animation
# (sdetorus.gif, generated by sdetorus-logo.R): the "sdetorus" wordmark is
# treated as a density and evolved by a Crank-Nicolson PDE, so at an intermediate
# step it appears as a colourful density heatmap (MATLAB "jet" colormap) that
# still reads as "sdetorus". This diffused wordmark *is* the badge, so no crisp
# package name is overlaid on top. The torus fundamental domain is a periodic
# square, which is why the square frame fills the whole hexagon (full-bleed).
#
# Run from within this logo/ directory:
#
#   Rscript sdetorus-hexsticker.R
#
# Requires: magick, hexSticker.

library(magick)
library(hexSticker)

## ---- Parameters -------------------------------------------------------------

gif_file  <- "sdetorus.gif"
frame_idx <- 84            # intermediate diffusion step (of 200): wordmark is
                           # sharp yet still a density, with a touch of warm jet
                           # accent. Try ~110 for a bolder, cooler variant.
border    <- "#08519C"     # deep jet-blue (cool end of matlab.like2)
fill      <- "#08306B"     # dark navy (mostly hidden behind the full-bleed frame)
ghurl     <- "github.com/egarpor/sdetorus"   # runs along the lower-right edge
out_logo  <- "sdetorus-hexlogo.png"
out_man   <- "../man/figures/logo.png"

## ---- 1. Intermediate frame from the diffusion gif ---------------------------

g     <- image_read(gif_file)
frame <- image_convert(g[frame_idx], "png")
frame <- image_resize(frame, "1000x1000", filter = "Lanczos")   # smooth upscale
ftmp  <- tempfile(fileext = ".png")
image_write(frame, ftmp, format = "png")

## ---- 2. Full-bleed hex sticker ----------------------------------------------

# hexSticker does not clip an oversized subplot to the hexagon, so a full-bleed
# square spills into the corners. We render (a) the full-bleed sticker and (b) a
# hexagon-only sticker with the same geometry, then use (b)'s silhouette as an
# alpha mask to crop (a) cleanly to the hexagon while keeping the border.
render <- function(subplot, s_width, url, file) {
  sticker(subplot = subplot, s_x = 1, s_y = 1,
          s_width = s_width, s_height = s_width,
          package = "",                         # wordmark already lives in the frame
          h_fill = fill, h_color = border, h_size = 1.8,
          url = url, u_x = 1.12, u_y = 0.15, u_angle = 30,  # diagonal, along lower-right edge
          u_size = 3.0, u_color = "#FFFFFF",
          filename = file, dpi = 600)
  invisible(file)
}

full_f <- tempfile(fileext = ".png")
render(ftmp, 1.0, ghurl, full_f)

blank  <- image_blank(4, 4, color = "none")     # transparent -> pure hex silhouette
btmp   <- tempfile(fileext = ".png")
image_write(blank, btmp, format = "png")
mask_f <- tempfile(fileext = ".png")
render(btmp, 0.1, "", mask_f)                   # no url on the mask (pure silhouette)

sticker_img <- image_composite(image_read(full_f), image_read(mask_f),
                               operator = "CopyOpacity")
image_write(sticker_img, out_logo, format = "png")

## ---- 3. Mirror to the conventional man/figures/logo.png ---------------------

dir.create(dirname(out_man), showWarnings = FALSE, recursive = TRUE)
image_write(sticker_img, out_man, format = "png")

message("Wrote ", out_logo, " and ", out_man,
        " (", image_info(sticker_img)$width, "x",
        image_info(sticker_img)$height, ")")
